---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Install rofi via apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # Cache update is a preparatory operation, not a state change
      become: true

    - name: Ensure rofi is installed
      community.general.apk:
        name: "{{ package }}"
        state: present
      loop: "{{ rofi_distro_pkgs }}"
      loop_control:
        loop_var: package
      become: true
