---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Checks rofi version in package manager
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # Cache update is a preparatory operation, not a state change
      become: true

    - name: Get rofi version from package manager
      ansible.builtin.command:
        cmd: "apk info {{ rofi_distro_pkgs[0] }}"
      changed_when: false
      failed_when: false
      ignore_errors: true
      register: rofi_pkg_mgr_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        rofi_pkg_mgr_version: "{{ (rofi_pkg_mgr_version_cmd.stdout | regex_search('rofi-([\\d\\.]+)', '\\1', multiline=True))[0] }}"

    - name: Debug rofi version from package manager
      ansible.builtin.debug:
        var: rofi_pkg_mgr_version
