---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Uninstall rofi from apk
  block:
    - name: Remove rofi if it is installed
      community.general.apk:
        name: "{{ package }}"
        state: absent
        no_cache: true
      loop: "{{ rofi_distro_pkgs }}"
      loop_control:
        loop_var: package
      become: true
